---
name: fiteens
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+1
  cupertino_icons: ^0.1.3
  lit_firebase_auth: ^0.2.3
  font_awesome_flutter: ^8.10.0
  google_fonts: ^1.1.1
  animations: ^1.1.2
  cloud_firestore: ^0.13.7
  argon_buttons_flutter: ^1.0.6
  flutter_spinkit: ^4.1.2+1
  fluttertoast: ^7.1.1
  flutter_launcher_icons: ^0.8.1
flutter_icons:
  image_path: "assets/icons/fiteenslogo.JPG"
  android: true
  ios: true
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
assets:
  - assets/
  - null
